package org.dergigi.offlineentropymanual.ui

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.LinkAnnotation
import androidx.compose.ui.text.SpanStyle
import androidx.compose.ui.text.TextLinkStyles
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.text.withLink
import androidx.compose.ui.unit.dp

const val SeedSafetyWarningText =
    "Never use a seed generated by a website or an app, or enter your seed into a " +
        "website or an app. Either can easily save the seed and use it to steal all " +
        "your bitcoins."

@Composable
fun SeedSafetyWarning(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Text(
            text = "Warning",
            style = MaterialTheme.typography.titleMedium,
            color = MaterialTheme.colorScheme.error,
        )
        Text(
            text = SeedSafetyWarningText,
            style = MaterialTheme.typography.bodyMedium,
            modifier = Modifier.padding(top = 8.dp),
        )
    }
}

@Composable
fun Bip39ChecksumNote(
    onOpenAirgappedDevice: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val linkColor = MaterialTheme.colorScheme.primary
    val note = buildAnnotatedString {
        append(
            "The last word of a BIP39 seed (the 12th or 24th) is a checksum. After you have " +
                "the first 11 or 23 words, calculate it on a hardware wallet that supports " +
                "that step, such as SeedSigner, BitBox02, or Blockstream Jade, or on some " +
                "other ",
        )
        withLink(
            LinkAnnotation.Clickable(
                tag = "airgapped-device",
                styles = TextLinkStyles(style = SpanStyle(color = linkColor)),
                linkInteractionListener = { onOpenAirgappedDevice() },
            ),
        ) {
            append("airgapped device")
        }
        append(". Do not use a website or phone app.")
    }

    Column(modifier = modifier) {
        Text(
            text = "Checksum",
            style = MaterialTheme.typography.titleMedium,
        )
        Text(
            text = note,
            style = MaterialTheme.typography.bodyMedium,
            modifier = Modifier.padding(top = 8.dp),
        )
    }
}
